version: '3'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - "8080:8080"
    command: ['start-dev']
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ./target/keycloak-2fa-email.jar
        target: /opt/keycloak/providers/keycloak-2fa-email.jar
